### ISSUE TITLE
project compile error

### ISSUE THREAD

**Issue by luhaoaimama1** [koral--/android-gif-drawable-sample#4]
compile error:
1.
import pl.droidsonroids.gif.GifOptions;
import pl.droidsonroids.gif.GifTexImage2D;
 2.
multiCallback= new MultiCallback(true);

I think  this project  is older?  I  want to see Newest,because I is first know this lib.I want to know more about this lib.so I need to see you sample ~

**Comment by koral--** [comment]
It seems that you have outdated library submodule. It can be updated eg. using `git submodule update`. Current HEAD is at commit: `52382bc062fb8fff5cd220c604e13b915bcdef51`. Here you can see how travis clones sample and submodule: https://travis-ci.org/koral--/android-gif-drawable-sample

**Comment by luhaoaimama1** [comment]
thanks
